### ISSUE TITLE
[BUG] Line point drawn outside of the graph

### ISSUE THREAD

**Issue by BlackYoup** [38/plotters#136]
**Describe the bug**
Hello,

I have an issue where sometimes, a line point is rendered on the left, in the Y absis column, of the graph instead of the end of the serie. You can check out this video: https://blackyoup.cellar-c2.services.clever-cloud.com/plotters-off-by-one.mp4 starting at ~8 seconds, you can see a blue point rendered between the 0 and 50 Y absis.

I've traced this a bit in the library and it seems like it's the **last** point of the serie that is drawn there. My image buffer is 758px width and 250px height and that's the same values that I give to the BitMapBackend: https://github.com/makers-for-life/makair/blob/5c8bb20cad9a9d1be4dde9c6a5c943c730891575/src/software/control/src/display/renderer.rs#L293

From what I see by tracing the code, it seems like the X value of this point is supposed to be drawn at pixel 758 which is the same size as my image buffer. But I find this value weird, to me, the image should only be drawn from pixel 0 to pixel 757, shouldn't it? This may be a side effect but if I replace this line https://github.com/38/plotters/blob/036520b9b8c30ae4f8b201f4c600bb62d05663b9/src/drawing/area.rs#L238 by `(self.rect.x1 - self.rect.x0 - 1) as u32,` the point doesn't render on the left.

I wanted to have your input before attempting any fixes as I'm not really sure the problem comes from what I described.

Am I doing something wrong here or is an off-by-one issue?

**To Reproduce**
You can checkout the https://github.com/makers-for-life/makair/ repository, go into `src/software/control` and run `cargo run -- -f ../telemetry/records/from_boot_with_fake_cycles_and_params_changes` (some errors will pop up because this file is outdated but the bug triggers on it. It's not the same file as I made the video with)

**Version Information**
Plotters 0.2.12 and master

Again, thanks a lot for your time :)

**Comment by 38** [comment]
Thanks for reporting this, this is a known bug of BitMapBackend, I am working on a fix and will let you know when it's fixed on master.

**Comment by 38** [comment]
Hi thanks for reporting this. By definition, this should be ``` (self.rect.x1 - self.rect.x0)```, since we use semi-open range at this point (But I am not sure if there's some place messed up).

But the correct behavior of out-of-range pixel is discard, but BitMapBackend has a known bug that draws the overflow pixel on the next row (this is caused by a boundary check bug within the fast drawing code in BitMapBackend).

I am going to work on the fix and hopefully it will get fixed with the next minor release.

I will let you guys updated on the fix and release. And please let me know if there's anything else I can do.

Thanks!

**Comment by 38** [comment]
Hi @BlackYoup , just made the fix, could you please confirm this is the correct fix?

BTW, I have a look at the use of plotters, note that a few place can be optimized for performance (If you guys really think performance is important).

- Plotters is able to manipulate the raw buffer directly, instead of render it in a different buffer, it's possible to create a bitmap backend on existing buffer if the pixel format matches. 
- Incremental rendering would be helpful in this use case, since you can only update the sub drawing area that is constantly changing.

I'm not sure if performance would be on your task list, but I just put this note here in case you need it.

Cheers!

**Comment by BlackYoup** [comment]
@38 Thanks!

I'm afraid the issue is still there, using latest master I still the some dots rendered outside of the graph.

Yes, performance is on our task list. To give you a bit more context, this UI will be run on a Raspberry 4 (at least for now) so we have a bit of resources but not that much. We currently target 30fps (which gives a frame every 32ms) and the rendering loop takes 20ms last time I checked (maybe a bit more now) so we are good for now but it should be improved if possible. Because the UI work mostly started a week ago, I did not take more time to improve it yet.

> Plotters is able to manipulate the raw buffer directly, instead of render it in a different buffer, it's possible to create a bitmap backend on existing buffer if the pixel format matches.

Isn't it what we are currently doing? We use the `BitMapBackend::with_buffer()` but maybe I'm missing something.

> Incremental rendering would be helpful in this use case, since you can only update the sub drawing area that is constantly changing.

Yes it could! I think I tried to use a `ChartState` at some point but failed to make it work, is it what's needed here? If yes, it's on my todo list to check again, I'm not sure what I did wrong last time but the graph rendered quite wrong, I only had the grid lines, no X / Y axes nor points series. I tried to reproduce the same code you used in the minifb-demo example.

Also, if I can borrow a bit more of your time, would you have any idea as to why the graph seems a bit "blurry" when rendered? I don't know if you had the chance to start the program but to me it seems the Y axis has its numbers (0 and 50 in our case) very pixelated. And the graph lines don't seem very "smooth". We were thinking maybe we lack some anti-aliasing somewhere or maybe that's the way we pass the data around. Would you have any pointer that I could look at? I have very few knowledge in that field so I may miss something very obvious. That's not something I took a good look at for now but I will in the next few days.

Thanks a lot for your time on those matters!

PS: In case you ever want to contribute to this project, we happily accept pull requests :) (even though you already are helping us a lot!)

**Comment by 38** [comment]
Oops, sorry I messed up a little bit - it should work after my latest fix. Please confirm this.

----

> Isn't it what we are currently doing? We use the `BitMapBackend::with_buffer()` but maybe I'm missing something.

https://github.com/makers-for-life/makair/blob/5c8bb20cad9a9d1be4dde9c6a5c943c730891575/src/software/control/src/display/renderer.rs#L290

For each time, a new buffer is allocated and we need to zero them and draw the text, etc. But actually plotters allows you to do that. 

Also Plotters allows to manipulate the framebuffer directly, which means we can actually update the image without copying the data around. Check the example here https://github.com/38/plotters/blob/master/examples/minifb-demo/src/main.rs (P.S. I also runs this demo targeting the framebuffer device on raspberry pi directly).

> Yes it could! I think I tried to use a `ChartState` at some point but failed to make it work, is it what's needed here?

Yes, you are right. ChartState is the way you can reuse the buffer, avoid creating ChartContext again and again, also save time for those drawing area that isn't changed (e.g. the drawing area for those labels, etc)

**Comment by 38** [comment]
> Also, if I can borrow a bit more of your time, would you have any idea as to why the graph seems a bit "blurry" when rendered? I don't know if you had the chance to start the program but to me it seems the Y axis has its numbers (0 and 50 in our case) very pixelated. And the graph lines don't seem very "smooth". We were thinking maybe we lack some anti-aliasing somewhere or maybe that's the way we pass the data around. Would you have any pointer that I could look at? I have very few knowledge in that field so I may miss something very obvious. That's not something I took a good look at for now but I will in the next few days.

I am suspecting you are just drawing too many data points on the plot, plotters renders line with anti-aliasing pixels, but if there are tiny lines (e.g. render to a single pixel) the algorithm just won't do anything to smooth it. So I think it's both performance and appearance gain if we can down-sample the data before it's fed into the chart. (It seems that your # of data points is larger than the # of pixel)

**Comment by BlackYoup** [comment]
> Oops, sorry I messed up a little bit - it should work after my latest fix. Please confirm this.

Seems like I still have the issue :-/ I'm not sure if I hit it a bit less or not. May it be related to the fact that we also try to draw more points than we have pixels?

> For each time, a new buffer is allocated and we need to zero them and draw the text, etc. But actually plotters allows you to do that.

Oh okay, I might have misunderstand you then. Yes that's also on my todo list, I tried to do that when also trying to use the ChartState to save the state.

> So I think it's both performance and appearance gain if we can down-sample the data before it's fed into the chart. (It seems that your # of data points is larger than the # of pixel)

Indeed, you might be right, I did not think it that way. I thought the more points I would have, the better the serie would be. I'll try this first, thanks for the input.

**Comment by 38** [comment]
> Seems like I still have the issue :-/ I'm not sure if I hit it a bit less or not. May it be related to the fact that we also try to draw more points than we have pixels?

On my side, I run ` cargo run -- -f ../telemetry/records/from_boot_with_fake_cycles_and_params_changes` 

It seems no pixel on the left side anymore.  

![image](https://user-images.githubusercontent.com/3023614/80636448-bb0a0400-8a1a-11ea-9eae-5eb62930013b.png)

My understand is this should be expected output or I was wrong?

**Comment by BlackYoup** [comment]
Mmh, I'm sorry but it seems fine now on my end too. I might not have cleaned my local environment before reporting, sorry. So I guess this issue is fixed!

Thank you very much :)

**Comment by 38** [comment]
No problem, I am so glad you guys find this crate is helpful in your ventilator project. Good luck and please let me know there's anything I can help !
